# Generated by Django 6.0.6 on 2026-07-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="demoimport",
            options={},
        ),
        migrations.AddField(
            model_name="demoimport",
            name="language",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
